services:
  postgres:
    image: postgres:latest
    restart: always
    environment: 
        - POSTGRES_USER=course
        - POSTGRES_PASSWORD=changeme
        - POSTGRES_DB=movies
    ports:
        - '5432:5432'

  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Movies.Api/Dockerfile
    ports:
        - "80:8080"
        - "81:8081"
    depends_on:
      - postgres
    # environment:
    #   - Database__ConnectionString=Host=postgres;Port=5432;Username=course;Password=changeme;Database=movies

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.Api/Dockerfile
    ports:
        - "6000:8080"
        - "6001:8081"

